version: "3.8"

services:
  db:
    image: mysql:8
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    ports:
      - '33306:3306'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: onboarding
      MYSQL_USER: choizz
      MYSQL_PASSWORD: ${PASSWORD}
      TZ: Asia/Seoul


  db-admin:
    container_name: db-adminer
    image: adminer:latest
    ports:
      - "18080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=hydra
      - ADMINER_PLUGINS=tables-filter tinymce

  app:
    container_name: onboarding-app
    build: ./
    restart: always
    ports:
      - '8081:8080'
    depends_on:
      - db