spring:
  jpa:
    hibernate:
      ddl-auto: none

## datasource,

jwt:
  secret-key : sdfsdfsdfesdfdf1111345dfesf6645454534545451
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 500