spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    username: choizz
    password: 1234
    url: jdbc:mysql://db:3306/onboarding
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: sdfsdfsdfesdfdf1111345dfesf664394820334545451
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 50


